mfact = 0.55
nmaster = 1
gappx = 10
layout = master-stack
movestep = 20
refreshrate = 120
workspaces = 7

notiledtitle = 0
decorhints = 1
borderpx = 1
verticaltitle = 0
inverttitlebar = 0
titleborderpx = 0
titleheight = 32
titlefont = monospace
fontsize = 13.00
outerpad = 6
invertbuttons = 0
lrpad = 10
centeredtitle = 1
offset_y = 1
buttonradius = 2
buttonwidth = 11
buttonheight = 11

iconfont = monospace
iconsize = 10.00
#btn_close_icn =
#btn_maximize_icn =
#btn_minimize_icn =
buttonborderpx = 0

bgnorm = #222222
bgsel = #2a2a2a

fgnorm = #999999
fgsel = #e0e0e0

bordernorm = #555555
bordersel = #6a6a6a
borderswaporig = #eeeeee
borderswapdest = #f1212c

titlebordernorm = #111111
titlebordersel = #151515

closefgnorm = #999999
closefgsel = #222222
closefghover = #222222

closebgnorm = #999999
closebgsel = #f1212c
closebghover = #f1414c

closebordernorm = #999999
closebordersel = #f1212c
closeborderhover = #f1414c

maximizefgnorm = #999999
maximizefgsel = #222222
maximizefghover = #222222

maximizebgnorm = #999999
maximizebgsel = #e0e0e0
maximizebghover = #ffffff

maximizebordernorm = #999999
maximizebordersel = #e0e0e0
maximizeborderhover = #ffffff

minimizefgnorm = #999999
minimizefgsel = #e0e0e0
minimizefghover = #222222

minimizebgnorm = #999999
minimizebgsel = #e0e0e0
minimizebghover = #e0e0e0

minimizebordernorm = #999999
minimizebordersel = #e0e0e0
minimizeborderhover = #e0e0e0

# ==========================================
# Workspace Rules
# ==========================================

# set the default values for a specific workspace
# 'Any' means all monitors
# name is only read by external programs, such as bars and pagers

# 		  num  name    monitor   layout	gappx  mfact  nmaster
# ws-rule = { 1,   home,  HDMI-0,  monocle,  10,    0.55,  1 }

# ==========================================
# Client Rules
# ==========================================

# set the default values for clients
# 'Any' can be used to not specify monitor/class/name

# 			   class    name monitor workspace floating sticky hasdecoration
# client-rule = { firefox, Any, Any,  2,        0,       0,     1 }
# client-rule = { steam,   Any, HDMI-1, 7,        0,       0,     0 }
